## Calibration Curve Uncertainty

### Overview

A quadratic fit has been applied on the uploaded data. For a general function \\(X=f(x_1,x_2,\\ldots,x_n)\\), the variance \\(Var(X)\\) by [Taylor's theorem](https://en.wikipedia.org/wiki/Taylor's_theorem) (first-order expansion) is given by:

\\(\\displaystyle Var(X) =
\\left(\\frac{\\partial X}{\\partial x_1}\\right)^2 Var(x_1) +
\\left(\\frac{\\partial X}{\\partial x_2}\\right)^2 Var(x_2) + \\ldots +
\\left(\\frac{\\partial X}{\\partial x_n}\\right)^2 Var(x_n) + \\\\
\\displaystyle \\hspace{3em} 
2\\left(\\frac{\\partial X}{\\partial x_1}\\right) \\left(\\frac{\\partial X}{\\partial x_2}\\right) Cov(x_1,x_2) +
2\\left(\\frac{\\partial X}{\\partial x_1}\\right) \\left(\\frac{\\partial X}{\\partial x_3}\\right) Cov(x_1,x_3) +
\\ldots
\\)


Using the approach described by <a href='https://doi.org/10.1039/B615398D' title='The uncertainty of a result from a linear calibration' target='_blank'>D. Brynn Hibbert: The uncertainty of a result from a linear calibration (2006)</a>, a quadratic  model of the form \\(y=b_0 + b_1x + b_2x^2\\) can be rewritten as \\(y - \\overline{y} = b_1(x-\\overline{x}) + b_2(x^2 - \\overline{x^2})\\) to make the curve start from the origin. Doing this removes the covariance dependence of \\(b_0\\) with \\(b_1\\) and \\(b_2\\).

Given an instrument response of case sample peak area ratio \\(y_s\\), the level of concentration \\(x_s\\) is estimated by solving for \\(x\\) as:

\\( \\displaystyle \\hat{x_s} = \\frac{ -b_1 \\sqrt{ b_1^2-4b_2( \\overline{y}-y_s-b_1 \\overline{x}-b_2 \\overline{x^2}) } } {2b_2} \\)

The standard uncertainty \\(u\\text{(CalCurve)}\\) is then obtained by apply Taylor's theorem to the variance of \\(\\hat{x}_s\\).

### Method

Using the approach described in <a href='https://doi.org/10.1039/B615398D' title='The uncertainty of a result from a linear calibration' target='_blank'>D. Brynn Hibbert: The uncertainty of a result from a linear calibration (2006)</a> the uncertainty of the quadratic curve is given by:

\\(\\displaystyle u\\text{(CalCurve)}^2 =
\\left(\\frac{\\partial \\hat{x_s}}{\\partial b_1}\\right)^2 Var(b_1) +
\\left(\\frac{\\partial \\hat{x_s}}{\\partial b_2}\\right)^2 Var(b_2) +
\\left(\\frac{\\partial \\hat{x_s}}{\\partial \\overline{y}}\\right)^2 Var(\\overline{y}) + \\\\
\\displaystyle \\hspace{3em}\\left(\\frac{\\partial \\hat{x_s}}{\\partial y_s}\\right)^2 Var(y_s) +
2\\left(\\frac{\\partial \\hat{x_s}}{\\partial b_1}\\right) \\left(\\frac{\\partial \\hat{x_s}}{\\partial b_2}\\right) Cov(b_1,b_2)\\)

**Note:** As described in the overview, this formula removes the covariance dependency of \\(b_0\\) with the other parameters \\(b_1\\) and \\(b_2\\) by making the model start from the origin <a href='https://doi.org/10.1039/B615398D' title='The uncertainty of a result from a linear calibration' target='_blank'>[Pg. 4/5 - D. Brynn Hibbert (2006)]</a>.

The Relative Standard Uncertainty is then given by:

\\(\\displaystyle u_r \\text{(CalCurve)} = \\frac{u \\text{(CalCurve)}}{x_s}\\)

The partial derivatives is obtained by differentiating the equation below with respect to \\(b_1, b_2, \\overline{y}, y_0\\)

\\(\\displaystyle \\hat{x_s} = \\frac{-b_1\\sqrt{b_1^2-4b_2( \\overline{y}-y_s-b_1 \\overline{x}-b_2 \\overline{x^2})}}{2b_2}\\)

**Note:** It is assumed that the regression parameters are independent and that \\(Var( \\overline{x}) = 0\\) and \\(Var( \\overline{x^2}) = 0\\).

The Covariance Matrix for \\(Var(b_1)\\), \\(Var(b_2)\\) and \\(Cov(b_1,b_2)\\) can be estimated as:

\\(\\sigma^2( \\underline{X}^T \\underline{X})^{-1} = 
\\begin{Bmatrix}
Var(b_0) & Cov(b_0,b_1) & Cov(b_0,b_2) \\\\
Cov(b_0,b_1) & Var(b_1) & Cov(b_1,b_2) \\\\
Cov(b_0,b_2) & Cov(b_1,b_2) & Var(b_2) \\\\
\\end{Bmatrix}\\)

where \\(\\sigma^2\\) is the variance of \\(y\\) estimated by the Standard Error of Regression squared \\(S_{y/x}^2\\):

\\(\\displaystyle S_{y/x} = \\sqrt{\\frac{\\sum\\limits_{i=1}^n (y_i-\\hat{y}_i)^2}{n-3}}\\)

- \\(x_i\\) concentration at level \\(i\\).
- \\(x_s\\) is the mean concentration of the Case Sample.
- \\(r_s\\) is the number of replicates made on test sample to determine \\(x_s\\).
- \\(y_i\\) observed peak area ratio for a given concentration \\(x_i\\).
- \\(\\hat{y}_i\\) predicted value of \\(y\\) for a given value \\(x_i\\).
- \\(b_1\\) is the Slope of the of regression line.
- \\(y_s\\) is the mean of Peak Area Ratio of the Case Sample.
- \\(n\\) is the number of measurements used to generate the Calibration Curve.
- \\(\\overline{x}\\) is the mean values of the different calibration standards.
- \\(Var(\\overline{y})\\) is the variance of the mean of \\(y\\), given as: \\(\\frac{S_{y/x}^2}{n}\\).
- \\(Var(y_s)\\) is the variance of the mean of Case Sample Peak Area Ratios \\((y_s)\\), given as:  \\(\\frac{S_{y/x}^2}{r_s}\\)

### Data
#### Calibration Curve
`r renderData(params$calibrationCurveData)`

### Calculations
```{r echo=FALSE,calibrationCurveDataReformatted, echo=FALSE, fig.cap="Concentration vs Peak Area Ratio", out.width = '80%', fig.align = 'center'}

data = params$calibrationCurveDataReformatted

if(!is.null(data))
{
  ggplot(data, aes(x = calibrationDataConcentration, y = calibrationDataPeakArea)) +
    geom_point() + 
    labs(x = "Concentration", y = "Peak Area Ratio") +
    geom_smooth(method='lm', formula=y~x+I(x^2))
}

```

***
Let discriminant (D) be equal to:

`r if(!is.na(params$display_calibrationCurveQuadratic_discriminant_renderer)) paste(params$display_calibrationCurveQuadratic_discriminant_renderer, "***")`

The partial derivatives are derived as:

`r if(!is.na(params$display_calibrationCurveQuadratic_partialDerivativeSlope1_renderer)) paste(params$display_calibrationCurveQuadratic_partialDerivativeSlope1_renderer, "***")`

`r if(!is.na(params$display_calibrationCurveQuadratic_partialDerivativeSlope2_renderer)) paste(params$display_calibrationCurveQuadratic_partialDerivativeSlope2_renderer, "***")`

`r if(!is.na(params$display_calibrationCurveQuadratic_partialDerivativeMeanOfY_renderer)) paste(params$display_calibrationCurveQuadratic_partialDerivativeMeanOfY_renderer, "***")`

`r if(!is.na(params$display_calibrationCurveQuadratic_partialDerivativeCaseSampleMeanPeakAreaRatio_renderer)) paste(params$display_calibrationCurveQuadratic_partialDerivativeCaseSampleMeanPeakAreaRatio_renderer, "***")`

`r if(!is.na(params$display_calibrationcurveQuadratic_quadraticRegression_renderer)) paste(params$display_calibrationcurveQuadratic_quadraticRegression_renderer, "***")`

The covariance matrix is given by:

`r if(!is.na(params$display_calibrationCurveQuadratic_covarianceMatrix_renderer)) paste(params$display_calibrationCurveQuadratic_covarianceMatrix_renderer, "***")`

`r if(!is.na(params$display_calibrationCurveQuadratic_uncertaintyOfCalibration_renderer)) paste(params$display_calibrationCurveQuadratic_uncertaintyOfCalibration_renderer, "***")`

`r params$display_calibrationCurveQuadratic_finalAnswer_bottom_renderer`

***