## Combined Uncertainty

### Overview

The combined uncertainty is obtained by combining all the individual uncertainty components.

If data is uploaded for all the uncertainty components; Homogeneity, Calibration Curve, Method Precision, Calibration Standard and Sample Preparation, relative standard uncertainty is computed for each uncertainty component and are combined to obtain the Combined Uncertainty of the analytical process.

If data is omitted for some uncertainty components, NA's will be displayed for those components and the Combined Uncertainty will only take into account components for which data is provided.

### Method
The combined uncertainty is given by:

$\text{CombUncertainty} = x_s \sqrt{\sum{u_r\text{(Individual Uncertainty Component)}^2}}$

- Where \(x_s\) is the Case Sample Mean Concentration.

### Calculations
```{r echo=FALSE,combinedUncertainty_uncertaintyBudget_graphData, echo=FALSE, fig.cap="Uncertainty Budget", out.width = '80%', fig.align = 'center'}

data = params$combinedUncertainty_uncertaintyBudget_graphData

ggplot(data, aes(x = percentage, y = reorder(uncertaintyComponent, percentage))) +
  geom_col(width = 0.7) + 
  labs(x = "Percentage", y = "Uncertainty Component")

```

***

`r params$combinedUncertainty_finalAnswer_renderer`

***