---
output: html_document

params:
  TIME: NA
  APP_DEV: NA
  APP_DEV_SHORT: NA
  APP_NAME: NA
  APP_NAME_SHORT: NA
  APP_VER: NA
  APP_LINK: NA
  calibrationCurveIsQuadratic: NA
  calibrationCurveData: NA
  calibrationCurveDataReformatted: NA
  externalStandardErrorData: NA
  methodPrecisionData: NA
  standardSolutionData: NA
  standardSolutionEquipmentData: NA
  samplePreparationData: NA
  homogeneityData: NA
  
  combinedUncertainty_uncertaintyBudget_graphData: NA
  
  usingManualCoverageFactor: NA
  
  inputWeightLeastSquared: NA
  customWls: NA
  customWlsPooled: NA
  inputCaseSampleReplicates: NA
  inputCaseSampleMeanConcentration: NA
  inputCaseSampleMeanPeakAreaRatio: NA
  inputCaseSampleWeight: NA
  inputConfidenceInterval: NA
  inputManualCoverageFactor: NA
  uncCalibrationCurve: NA
  uncMethodPrecision: NA
  uncStandardSolution: NA
  uncSamplePreparation: NA
  uncHomogeneity: NA
  homogeneityTestResult: NA
  homogeneityTestAlphaValue: NA
  homogeneityTestDofW: NA
  homogeneityTestDofB: NA
  homogeneityTestFStat: NA,
  homogeneityTestFCrit: NA
  combinedUncertaintyResult: NA
  coverageFactorResult: NA
  expandedUncertaintyResult: NA
  expandedUncertaintyResultPercentage: NA
  
  calibrationCurve_linearRegression_renderer: NA
  calibrationCurve_uncertaintyOfCalibration_renderer: NA
  calibrationCurve_finalAnswer_bottom_renderer: NA
  
  display_calibrationCurveQuadratic_discriminant_renderer: NA
  display_calibrationCurveQuadratic_partialDerivativeSlope1_renderer: NA
  display_calibrationCurveQuadratic_partialDerivativeSlope2_renderer: NA
  display_calibrationCurveQuadratic_partialDerivativeMeanOfY_renderer: NA
  display_calibrationCurveQuadratic_partialDerivativeCaseSampleMeanPeakAreaRatio_renderer: NA
  display_calibrationcurveQuadratic_quadraticRegression_renderer: NA
  display_calibrationCurveQuadratic_covarianceMatrix_renderer: NA
  display_calibrationCurveQuadratic_uncertaintyOfCalibration_renderer: NA
  display_calibrationCurveQuadratic_finalAnswer_bottom_renderer: NA
  
  homogeneity_standardUncertainty_left_renderer: NA
  homogeneity_standardUncertainty_right_renderer: NA
  homogeneity_standardUncertainty_max_renderer: NA
  homogeneity_relativeStandardUncertainty_renderer: NA
  
  homogeneityTest_fValue_renderer: NA
  homogeneity_fCritical_renderer: NA
  renderHomogeneityTestAnswer: NA
  
  outputPooledStandardDeviation_renderer: NA
  outputStandardUncertainty_renderer: NA
  outputRealtiveStandardUncertainties_renderer: NA
  methodPrecision_finalAnswer_bottom_renderer: NA
  
  standardSolution_solutionRelativeStandardUncertainty_renderer: NA
  standardSolution_finalAnswer_renderer: NA
  
  samplePreparation_standardUncertainty_renderer: NA
  samplePreparation_relativeStandardUncertainty_renderer: NA
  samplePreparation_finalAnswer_bottom_renderer: NA
  
  combinedUncertainty_finalAnswer_renderer: NA
  coverageFactor_effectiveDegreesOfFreedom_renderer: NA
  coverageFactor_finalAnswer_bottom_renderer: NA
  expandedUncertainty_finalAnswer_renderer: NA
  
title: "`r params$APP_NAME` Report"
---

<!--
###########################################################################
#
# Measurement Uncertainty Calculator - Copyright (C) 2019
# Leverhulme Research Centre for Forensic Science
# Roy Mudie, Joyce Klu, Niamh Nic Daeid
# Website: https://github.com/LRCFS/lrcfs-measurement-uncertainty-calculator/
# Contact: lrc@dundee.ac.uk
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###########################################################################
-->

```{css, echo=FALSE}

@media print {
  .main-container{
    max-width: none;
  }
  .container-fluid
  {
    padding: 0;
  }
  
  .smallForPrint{
    font-size: 10pt !important;
  }
}

.icon-large{
  display: none;
}
```

```{r loadPackages, include=FALSE}
library("ggplot2")

renderData = function(data)
{
  if(!is.null(data)) knitr::kable(data, format="markdown") else paste("No data provided.")
}
```

```{r part_coverPage, child='coverPage.Rmd', eval=TRUE}
``` 
\newpage

## Summary
The following is a summary of the supplied data and results calculated.

```{r part_summary, child='summary_homogeneityTest.Rmd', eval=!is.na(params$uncHomogeneity)}
``` 
```{r part_summary, child='summary_measurementUncertainty.Rmd', eval=TRUE}
```

\newpage

# Methodology

```{r part_homogeneity, child='homogeneity.Rmd', eval=!is.na(params$uncHomogeneity)}
``` 

```{r part_calibrationCurve, child='calibrationCurve.Rmd', eval=!params$calibrationCurveIsQuadratic && !is.na(params$uncCalibrationCurve)}
```
```{r part_calibrationCurveQuadratic, child='calibrationCurveQuadratic.Rmd', eval=params$calibrationCurveIsQuadratic && !is.na(params$uncCalibrationCurve)}
```

```{r part_methodPrecision, child='methodPrecision.Rmd', eval=!is.na(params$uncMethodPrecision)}
```

```{r part_calibrationStandard, child='calibrationStandard.Rmd', eval=!is.na(params$uncStandardSolution)}
```

```{r part_samplePreparation, child='samplePreparation.Rmd', eval=!is.na(params$uncSamplePreparation)}
```

```{r part_combinedUncertainty, child='combinedUncertainty.Rmd', eval=TRUE}
```

```{r part_coverageFactor, child='coverageFactor.Rmd', eval=!params$usingManualCoverageFactor}
```

```{r part_expandedUncertainty, child='expandedUncertainty.Rmd', eval=TRUE}
```

# END OF REPORT